# NumPy Practical Problem Solving



In [1]:
import numpy as np
print('NumPy Version:', np.__version__)

NumPy Version: 1.26.4


## Problem 1: Replace Negative Values with Zero

In [2]:
arr = np.array([10, -5, 20, -3, 15, -8])
arr[arr < 0] = 0
print(arr)

[10  0 20  0 15  0]


## Problem 2: Find Second Largest Element

In [3]:
arr = np.array([10, 45, 67, 23, 89, 34])
first_max = np.max(arr)
second_max = np.max(arr[arr != first_max])
print(second_max)

67


##  Problem 3: Count Frequency of Elements

In [4]:
arr = np.array([1,2,2,3,4,4,4,5])
unique, counts = np.unique(arr, return_counts=True)
for u, c in zip(unique, counts):
    print(u, ':', c)

1 : 1
2 : 2
3 : 1
4 : 3
5 : 1


##  Problem 4: Find Duplicate Elements

In [5]:
arr = np.array([1,2,3,4,2,5,6,3,7])
unique, counts = np.unique(arr, return_counts=True)
duplicates = unique[counts > 1]
print(duplicates)

[2 3]


##  Problem 5: Row with Maximum Sum

In [6]:
matrix = np.array([[10,20,30],[40,50,60],[5,10,15]])
row_sums = np.sum(matrix, axis=1)
print('Row Index:', np.argmax(row_sums))
print('Row:', matrix[np.argmax(row_sums)])

Row Index: 1
Row: [40 50 60]


##  Problem 6: Column-wise Normalization

In [7]:
matrix = np.array([[10,200],[20,300],[30,400]])
normalized = (matrix - np.min(matrix, axis=0)) / (np.max(matrix, axis=0) - np.min(matrix, axis=0))
print(normalized)

[[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]


##  Problem 7: Matrix Diagonal Sum

In [8]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.sum(np.diag(matrix)))

15


##  Problem 8: Reverse Matrix Rows

In [9]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[:, ::-1])

[[3 2 1]
 [6 5 4]
 [9 8 7]]


##  Problem 9: Solve Linear Equation (Ax = B)

In [10]:
A = np.array([[3,1],[1,2]])
B = np.array([9,8])
solution = np.linalg.solve(A, B)
print(solution)

[2. 3.]


##  Problem 10: Create Checkerboard Pattern

In [11]:
checkerboard = np.zeros((8,8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


##  Problem 11: Softmax Function

In [13]:
def softmax(x):
    exp_values = np.exp(x - np.max(x))
    return exp_values / np.sum(exp_values)

arr = np.array([2.0, 1.0, 0.1])
print(softmax(arr))

[0.65900114 0.24243297 0.09856589]


##  Mini Data Science Practice

In [14]:
np.random.seed(0)
marks = np.random.randint(0, 101, 1000)

print('Average:', np.mean(marks))
print('Above 80:', np.sum(marks > 80))

grades = np.where(marks >= 90, 'A',
         np.where(marks >= 75, 'B',
         np.where(marks >= 50, 'C', 'Fail')))

print('Sample Grades:', grades[:10])

Average: 50.13
Above 80: 203
Sample Grades: ['Fail' 'Fail' 'C' 'C' 'C' 'Fail' 'B' 'Fail' 'Fail' 'B']
