# 📘 NumPy Complete Practice 


This notebook covers NumPy package with examples and practice problems.

In [1]:
import numpy as np
print('NumPy Version:', np.__version__)

NumPy Version: 1.26.4


## 1️ Creating NumPy Arrays

In [2]:
# 1D Array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

# 2D Array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

# 3D Array
arr3 = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(arr3)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## 2️ Array Properties

In [3]:
arr = np.array([[10, 20, 30], [40, 50, 60]])
print('Shape:', arr.shape)
print('Dimensions:', arr.ndim)
print('Size:', arr.size)
print('Data Type:', arr.dtype)

Shape: (2, 3)
Dimensions: 2
Size: 6
Data Type: int32


## 3️ Special Arrays

In [4]:
print(np.zeros((2,3)))
print(np.ones((3,3)))
print(np.eye(3))
print(np.arange(0, 10, 2))
print(np.linspace(0, 1, 5))
print(np.random.rand(3,3))
print(np.random.randint(1, 100, (3,3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[0.90696371 0.54406665 0.18419168]
 [0.08793961 0.84966053 0.0820823 ]
 [0.96393212 0.65937222 0.80556885]]
[[ 1 17  2]
 [77  6 83]
 [59 19 26]]


## 4️ Indexing and Slicing

In [5]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])
print(arr[-1])
print(arr[1:4])

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2[0,1])
print(arr2[:,1])

10
50
[20 30 40]
2
[2 5]


## 5️ Reshaping Arrays

In [6]:
arr = np.arange(1, 13)
reshaped = arr.reshape(3,4)
print(reshaped)
print(reshaped.flatten())

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


## 6️ Mathematical Operations

In [7]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print('Addition:', arr1 + arr2)
print('Subtraction:', arr1 - arr2)
print('Multiplication:', arr1 * arr2)
print('Division:', arr1 / arr2)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


## 7️ Statistical Functions

In [8]:
arr = np.array([10, 20, 30, 40, 50])
print('Mean:', np.mean(arr))
print('Median:', np.median(arr))
print('Standard Deviation:', np.std(arr))
print('Minimum:', np.min(arr))
print('Maximum:', np.max(arr))
print('Sum:', np.sum(arr))

Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951
Minimum: 10
Maximum: 50
Sum: 150


## 8️ Axis Operations

In [9]:
arr = np.array([[1,2,3],[4,5,6]])
print('Sum column-wise:', np.sum(arr, axis=0))
print('Sum row-wise:', np.sum(arr, axis=1))

Sum column-wise: [5 7 9]
Sum row-wise: [ 6 15]


## 9️ Boolean Indexing

In [10]:
arr = np.array([10, 25, 30, 45, 60])
print(arr > 30)
print(arr[arr > 30])

[False False False  True  True]
[45 60]


## 10 Broadcasting

In [11]:
arr = np.array([1,2,3])
print(arr + 10)

arr2 = np.array([[1],[2],[3]])
arr3 = np.array([10,20,30])
print(arr2 + arr3)

[11 12 13]
[[11 21 31]
 [12 22 32]
 [13 23 33]]


## 11 Linear Algebra (Advanced)

In [12]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print('Matrix Multiplication:\n', np.dot(A,B))
print('Determinant:', np.linalg.det(A))
print('Inverse:\n', np.linalg.inv(A))
print('Eigenvalues:', np.linalg.eig(A)[0])

Matrix Multiplication:
 [[19 22]
 [43 50]]
Determinant: -2.0000000000000004
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues: [-0.37228132  5.37228132]


##  Practice Problems

In [13]:
# Top 3 Highest Marks
marks = np.array([45, 78, 88, 92, 67, 81])
print('Top 3:', np.sort(marks)[-3:])

# Normalize Data
data = np.array([10, 20, 30, 40, 50])
normalized = (data - np.min(data)) / (np.max(data) - np.min(data))
print('Normalized Data:', normalized)

# Even Numbers 1–100
numbers = np.arange(1, 101)
even = numbers[numbers % 2 == 0]
print(even)

Top 3: [81 88 92]
Normalized Data: [0.   0.25 0.5  0.75 1.  ]
[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
